root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/app ./cmd/app/main.go"
  bin = "tmp/app"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]
[screen]
  clear_on_rebuild = true